### ISSUE TITLE
ShinyProxy-operator with custom ShinyProxy instance

### ISSUE THREAD

**Issue by templary** [openanalytics/shinyproxy-operator#23]
Hello,

I would like to ask you for some advice on the shinyproxy operator. 

About my environment: I am using a modified version of ShinyProxy running in kubernetes. The version is based on container proxy 0.8.8 and ShinyProxy 2.5.0.

1) Is it possible to use Operator with a custom version of ShinyProxy and if you can direct me how to implement this.

2) Is it also possible to use Operator to replace the whole ShinyProxy in case of an update of my own version of the application (ShinyProxy new version)?

Thank you very much for your advice.

**Comment by LEDfan** [comment]
Hi

Nice to hear you are interested in the operator! Regarding your questions:

1. yes, this is not a problem as long as you don't change the interaction between the operator and ShinyProxy (for example the labels added by ShinyProxy to a pod). You will need to build a custom Docker image of ShinyProxy, you can use our official Dockerfiles for this (https://github.com/openanalytics/shinyproxy-docker) (you don't have to build a custom image for the operator). Finally, you have to configure the name of the image in your ShinyProxy resource, for example: https://github.com/openanalytics/shinyproxy-operator/blob/master/docs/deployment/overlays/1-namespaced-hpa/shinyproxy/shinyproxy.yaml#L89
2. yes, every time the operator deploys a new ShinyProxy server it uses the docker image specified in the `image` field (see previous answer). Therefore, when you change this field, the operator will use the new image for the new deployment.

**Comment by templary** [comment]
Thank you a lot for your advice!
