### ISSUE TITLE
Conflict with AWS Ingress Controller

### ISSUE THREAD

**Issue by jboutwell-rva** [openanalytics/shinyproxy-operator#37]
I've been attempting to use the shinyproxy-operator in a new EKS cluster.  I had issues with the operator being able to communicate with the shinyproxy container and looking at operator logs I see:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1/apis/networking.k8s.io/v1/namespaces/shinyproxy/ingresses. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io "skipper" not found.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[shinyproxy-operator.jar:1.1.0]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[shinyproxy-operator.jar:1.1.0]
```

After much digging it appears to be related to the change to use `ingressClassName: skipper` as opposed to `kubernetes.io/ingress.class: "skipper"` with version 1.1.0.  I don't think this itself is an issue, but the AWS ALB webhook does not seem to agree.  I can isolate that change as I cannot create a standalone Ingress with `ingressClassName` in the cluster without it also failing for the same error.  I can't find any related issue online in either skipper or AWS ingress issues, but adding the following IngressClass finally resolved it.

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: skipper
spec:
  controller: k8s.io/skipper # Arbitrary?
```

I'm outside of my expertise with Kubernetes and Ingress to understand what is the issue (and likely some nuance of AWS Ingress), and I don't know if the above IngressClass will result in other unforeseen issues.  Is there something I am miss understanding?  Have others run up against any issues when using AWS Ingress?  Thanks!

Setup details:
EKS / Kubernetes version 1.23
ShinyProxy Operator version 1.1.0
Applied the `2-namespaced-ds` (or near identical) configuration

Other attempts to fix that failed:
Reverting to ShinyProxy Operator 1.0.x (failed because of incompatability with Kubernetes 1.23)
Upgrading skipper to version 0.14.x (no effect)
Using hpa instead of ds (same error)
Banging head into wall (pain)

**Comment by LEDfan** [comment]
Unfortunately we don't have experience with the AWS Ingress controller. However, we recently released version 2 of the operator which no longer requires Skipper. Therefore I would like to ask to re-try using the latest version of the operator.

**Comment by LEDfan** [comment]
Thank you for reporting back! I'm very happy to hear that both the old and new version works fine.
