### ISSUE TITLE
Clustered Skipper ingress deployment file is identical to the namespaced configuration

### ISSUE THREAD

**Issue by AndreyMatveyev** [openanalytics/shinyproxy-operator#4]
After using the instuctions at openanalytics/shinyproxy-operator/tree/develop/docs/deployment/README.md, following the 'clustered' path and using the deployment scripts at openanalytics/shinyproxy-operator/tree/develop/docs/deployment/clustered
The attempt to open the demo application https://shinyproxy-demo.local/ was returning the 404 Not Found error.
The detailed inspection of the clustered deployment scripts and the Skipper documentation section [Scoping Skipper Deployments to a Single Namespace](https://github.com/zalando/skipper/blob/master/docs/kubernetes/ingress-controller.md#scoping-skipper-deployments-to-a-single-namespace) revealed a problem in the deployment file https://github.com/openanalytics/shinyproxy-operator/blob/develop/docs/deployment/clustered/dependencies/deployment.yaml
This file is identical to the file https://github.com/openanalytics/shinyproxy-operator/blob/develop/docs/deployment/namespaced/dependencies/deployment.yaml which represents the configuration for the namespaced mode.
Simply removing 
```        
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
and 
```
         - "-kubernetes-namespace=$(KUBE_NAMESPACE)"
```
in the file https://github.com/openanalytics/shinyproxy-operator/blob/develop/docs/deployment/clustered/dependencies/deployment.yaml
fixed the problem

**Comment by LEDfan** [comment]
Hi

Thank you for your report! The configuration was indeed wrong and your solution is correct. Some time ago I updated the configuration according to our internal deployments, but copied the wrong code into clustered.

I'm looking forward to any other feedback on the operator.

Fixed in https://github.com/openanalytics/shinyproxy-operator/commit/d700196bb5cbb3d61ac88e718f57e68b2168b68d
