### ISSUE TITLE
Operator does not update ConfigMap

### ISSUE THREAD

**Issue by clemenschuaccso** [openanalytics/shinyproxy-operator#48]
Version: v2.0.0
Kubernetes version: 1.28.6-eks-508b6b3

At the beginning changing the CRD causes the config map to change without any problems, but after some uptime e.g. 4 months, changes from the CRD are not transferred to the ConfigMap, resulting in missing applications.

Restarting the operator pod by deleting it resolved the issue temporarily.

Log of the not working operator pod:
`13:41:25.377 [-2-thread-40176] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Watching https://172.20.0.1:443/apis/networking.k8s.io/v1/namespaces/rshiny/ingresses?resourceVersion=58322840&allowWatchBookmarks=true&watch=true...
13:41:25.453 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket successfully opened
13:57:53.055 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyListener       - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Event/Update]
13:57:53.116 [-2-thread-40179] INFO  eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 0/6: Ok] ReconcileSingleShinyProxy
13:57:53.116 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 1/6: Ok] [Component/ConfigMap]
13:57:53.116 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 2/6: Ok] [Component/ReplicaSet]
13:57:53.116 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 3/6: Ok] [Component/ReplicaSet] ReplicaSet ready
13:57:53.117 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 4/6: Ok] [Status/LatestMarker]
13:57:53.170 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 5/6: Ok] [Component/Service]
13:57:53.170 [-2-thread-40179] DEBUG eu.op.sh.co.ShinyProxyController     - [rshiny/shinyproxy/9a7800cac834c8d9d51accfad8da312b95147e6c] [Step 6/6: Ok] [Component/Ingress]
13:59:43.456 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket close received. code: 1000, reason:
13:59:43.456 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Scheduling reconnect task
13:59:43.456 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Current reconnect backoff is 1000 milliseconds (T0)
13:59:44.456 [-2-thread-40180] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Watching https://172.20.0.1:443/api/v1/namespaces/rshiny/services?resourceVersion=58328812&allowWatchBookmarks=true&watch=true...
13:59:44.512 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket successfully opened
14:11:31.202 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket close received. code: 1000, reason:
14:11:31.202 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Scheduling reconnect task
14:11:31.203 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Current reconnect backoff is 1000 milliseconds (T0)
14:11:32.203 [-2-thread-40182] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Watching https://172.20.0.1:443/apis/apps/v1/namespaces/rshiny/replicasets?resourceVersion=58332686&allowWatchBookmarks=true&watch=true...
14:11:32.256 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket successfully opened
14:16:27.809 [/172.20.0.1/...] DEBUG ku.cl.ds.in.WatcherWebSocketListener - WebSocket close received. code: 1000, reason:
14:16:27.809 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Scheduling reconnect task
14:16:27.809 [/172.20.0.1/...] DEBUG .fa.ku.cl.ds.in.AbstractWatchManager - Current reconnect backoff is 1000 milliseconds (T0)`

**Comment by LEDfan** [comment]
Hi, we were aware of this issue, it should be fixed in the next release, which will be released soon. 
In the meantime you can use a snapshot version: `openanalytics/shinyproxy-operator-snapshot:2.1.0-SNAPSHOT-20240405.092413`. Could you let us know whether this releases fixes it for you?
