### ISSUE TITLE
Favicon or bookmark icon

### ISSUE THREAD

**Issue by mth003** [openanalytics/shinyproxy-operator#52]
Hi, is it possible to utilize favicons by specifying `proxy.favicon-path` in  `shinyproxy.shinyproxy.yaml`? If so, how would this work and where would I need to copy the favicon.png file? The intent is for users to see the new bookmark icon after bookmarking the main landing page.

Thanks in advance.

**Comment by LEDfan** [comment]
Hi, yes this is possible. You must place the favicon file in the working directory of ShinyProxy (usually this is the same location as the `application.yml`). E.g. if you add `myfavicon.png`, you add the config `proxy.favicon-path: myfavicon.png`
