### ISSUE TITLE
Setting a "nodeselector"

### ISSUE THREAD

**Issue by mth003** [openanalytics/shinyproxy-operator#55]
Hi, 

We are trying to set the proxy.nodeselector option as described here: 
https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#create-a-pod-that-gets-scheduled-to-your-chosen-node

```
proxy:
   nodeSelector:
      kubernetes.io/os: linux
```

But this doesn't seem to be working. I suspect this needs to be added as a `kubernetes-pod-patches` or `kubernetesPodTemplateSpecPatches` instead? We want to have this nodeSelector to ensure pods get assigned to Linux type nodes on the cluster. Any suggestions? Here's what our yaml looks like

![image](https://github.com/user-attachments/assets/d0dab21e-43f6-4fff-a9ea-ea4c0a4facb9)

Thanks!

**Comment by LEDfan** [comment]
Hi, please see the shinyproxy docs: https://shinyproxy.io/documentation/configuration/#node-selector . You are using an incorrect syntax, the value of the property should be a string.
