### ISSUE TITLE
Shinyproxy pod created by operator uses wrong application.yml

### ISSUE THREAD

**Issue by abinet** [openanalytics/shinyproxy-operator#6]
I am trying to follow the docs for namespace scoped installation.
However it seems that the shinyproxy pod created by operator uses docker image application.yml from /opt/shinyproxy folder instead of configmap mounted into /etc/shinyproxy/application.yml.

**Comment by aupadh12** [comment]
I tried using the clustered scoped installation and the same issue happens to be happening over there as well.
I am using openid to configure the SSO using Azure AD but still, it is asking me for userid and password.

**Comment by LEDfan** [comment]
Hi

You have to use the latest version of the operator (`openanalytics/shinyproxy-operator-snapshot:0.0.1-SNAPSHOT-20210302.095930`) , the documentation was not yet updated for this.

**Comment by aupadh12** [comment]
Hi @LEDfan ,

That worked for me. Thank you.
